apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kubectl
    image: joshendriks/alpine-k8s
    command:
      - /bin/cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
      - /busybox/cat
    tty: true
  - name: git
    image: alpine/git
    command: ["cat"]
    tty: true
  - name: helm-cli
    image: ibmcom/k8s-helm:v2.6.0
    command: ["cat"]
    tty: true
#      volumemounts:
#        - name: kaniko-secret
#          mountPath: /kaniko/.docker
#  volumes:
#    - name: kaniko-secret
#      secret:
#        secretName: regcred
#        items:
#          - key: .dockerconfigjson
#            path: config.json
