apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
      - /busybox/cat
    tty: true
  - name: helm-cli
    image: lachlanevenson/k8s-helm:v3.9.4
    command: ["cat"]
    tty: true
